name: "Check compilation"

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Lint
        run: npm run lint

      - name: Run Build
        run: pnpm run build
